### ISSUE TITLE
Undo behavior of extendable block is weird

### ISSUE THREAD

**Issue by FurryR** [FurryR/lpp-scratch#1]
# en-us

## What is it?

Undoing an extendable block results unintended displaying and probably breaks the editor.

## Why it can't be fixed?

Unfortunately `Blockly` doesn't provide an API to handle `undo` behavior and I can't figure out how to prevent undo.

## Note

If you are able to fix, please navigate to `src/blockly/definition.ts` and modify the definition about `lpp_constructFunction`, etc.

Please do not open an issue about this bug. You won't get help.

# zh-cn

## 发生什么了？

撤销一个可扩展块（注：函数、数组等）将导致显示错误并（可能）会导致编辑器崩溃。

## 为什么不修复？

不幸的是，`Blockly` 没有提供任何 API 来处理撤销行为，并且我无法找到阻止撤销的方法。

## 注意

如果您可以修复这个 bug，请转到 `src/blockly/definition.ts` 然后修改 `lpp_constructFunction` 等块的定义。

请不要因为这个问题开 issue。您将不会得到帮助。

**Comment by Drago-Cuven** [comment]
take lessons from cst1229. he made an extendable blocks extension that works just fine for me.
